// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU_SmvpCOeb5cnJL1ANxF30sH55e2yHwA',
    appId: '1:627378669023:web:a170754cda00912bcab06a',
    messagingSenderId: '627378669023',
    projectId: 'instagraph-kian',
    authDomain: 'instagraph-kian.firebaseapp.com',
    storageBucket: 'instagraph-kian.appspot.com',
    measurementId: 'G-HD21JQQVT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhgYjyZbDP4y-HebYwKxfcS-GKGV8of3k',
    appId: '1:627378669023:android:b4b07b4c73c53c24cab06a',
    messagingSenderId: '627378669023',
    projectId: 'instagraph-kian',
    storageBucket: 'instagraph-kian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu0UXf2iEpz49L4eMi_GmeIRiI0DNNBXQ',
    appId: '1:627378669023:ios:f3f0fab6a78feacccab06a',
    messagingSenderId: '627378669023',
    projectId: 'instagraph-kian',
    storageBucket: 'instagraph-kian.appspot.com',
    iosClientId: '627378669023-vteqruvjkajut1tq1t00j7udusfbaj9b.apps.googleusercontent.com',
    iosBundleId: 'ir.coderats.instagraph',
  );
}
